export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILED';
export const SORT_DATA_ASCENDING = 'SORT_DATA_ASCENDING';
export const SORT_DATA_DESCENDING = 'SORT_DATA_DESCENDING';
